In [4]:
#Question 1 Function to perform exception: 

def devided(x,y):
    try:
        dev= x/y
        print("Ans is:", dev)
    except:
        print("Oops! something went wrong")
        
Operation = devided(10,8)

Ans is: 1.25


In [3]:
#computing as per assignment value
Operation = devided(5,0)

Oops! something went wrong


In [23]:
#Question 2:

subject=["Americans", " Indians"]
verb=["Play", "Watch"]
obj=["Baseball", "Cricket"]
Sentences_list = [(subjects + " " + verbs + " " + objects) for sub in subjects for ver in verbs for obj in objects]
for sen in Sentences_list:
    print(sen)             

TypeError: can only concatenate list (not "str") to list

In [3]:
#Question 2 : List Comprehension

subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
    print(sentence)


Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [2]:
#Question 2: Sentences with Iteration

subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

sentences = []

for sub in subject:
    for ver in verb:
        for ob in obj:
            sentences = sub+ " " + ver +" " +ob
            print(sentences)
            


Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [34]:
# Task 2 question :
import numpy as np
np.vander(x,N= None, increasing= "False")

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [36]:
x = np.array([1,2,3,4])
N= len(x)
np.vander(x,N)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [35]:
np.column_stack([x**(N-i-1) for i in range(N)])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]], dtype=int32)